PROGRAM_NAME = main

OBJECT_FILES = $(PROGRAM_NAME).o

CFLAGS = -O2 -Wall -g -I


clean :
    $(RM) $(PROGRAM_NAME)
    $(RM) $(OBJECT_FILES)

run:    ${PROGRAM_NAME}
        ./${PROGRAM} ${ARGS}




